# Generated by Django 4.1.2 on 2022-10-28 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concessionaria', models.CharField(choices=[('LIGHT', 'Light')], max_length=5)),
                ('subgrupo', models.CharField(choices=[('A2', 'A2'), ('A4', 'A4'), ('A5', 'A5')], max_length=2)),
                ('energia_utilizada_p', models.PositiveIntegerField()),
                ('energia_utilizada_fp', models.PositiveIntegerField()),
                ('potencia_utilizada_p', models.PositiveIntegerField()),
                ('potencia_contratada', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
