# Generated by Django 4.1.3 on 2022-11-09 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_user_dado_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='data_tempo',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
