# Generated by Django 4.1 on 2022-10-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concessionaria', models.PositiveSmallIntegerField(choices=[('1', 'Light')])),
                ('subgrupo', models.PositiveSmallIntegerField(choices=[('1', 'A2'), ('2', 'A4'), ('3', 'A5')])),
                ('energia_utilizada_p', models.PositiveIntegerField()),
                ('energia_utilizada_fp', models.PositiveIntegerField()),
                ('potencia_utilizada_p', models.PositiveIntegerField()),
                ('potencia_contratada', models.PositiveIntegerField()),
            ],
        ),
    ]
