# Generated by Django 4.1 on 2022-10-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concessionaria', models.CharField(choices=[('1', 'Light')], max_length=255)),
                ('subgrupo', models.CharField(choices=[('1', 'A2'), ('2', 'A4'), ('3', 'A5')], max_length=255)),
                ('energia_utilizada_p', models.PositiveIntegerField()),
                ('energia_utilizada_fp', models.PositiveIntegerField()),
                ('potencia_utilizada_p', models.PositiveIntegerField()),
                ('potencia_contratada', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Dados',
        ),
    ]
