# Generated by Django 4.1 on 2022-10-14 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=20)),
                ("email", models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Modalidade_Tarifaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Regiao_Militar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="dado_mensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.CharField(max_length=10)),
                ("consumo", models.FloatField()),
                ("demanda", models.FloatField()),
                (
                    "quartel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="clientes.cliente",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cliente",
            name="Regiao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="clientes.regiao_militar",
            ),
        ),
    ]
