# Generated by Django 4.1 on 2022-10-25 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Regiao',
        ),
        migrations.RemoveField(
            model_name='dado_mensal',
            name='quartel',
        ),
        migrations.DeleteModel(
            name='Modalidade_Tarifaria',
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
        migrations.DeleteModel(
            name='dado_mensal',
        ),
        migrations.DeleteModel(
            name='Regiao_Militar',
        ),
    ]
